### ISSUE TITLE
Question: Why are the functions to colorize the XP bar commented out

### ISSUE THREAD

**Issue by matronator** [bengriepp/codexp#1]
Hi, I forked your extension and I'm intending to expand upon it and found there are some functions commented out for setting the bar color. May I ask why are they commented out? Did it not work this way or is there some other issue with it?

**Comment by kitgore** [comment]
Yeah I originally had fade transitions for displaying messages (you can see in the readme a gif of what I'm talking about) using a hacky way to detect the theme colors and setting the bar color with different opacitys. It ended up not working when I deployed it, I think the colors would come out of sync when you changed themes or something along those lines I don't quite remember, so I ended up just removing it. But yeah feel free to expand on it, maybe there's better support for detecting color themes now if you want to try reimplementing it. If you want me to publish the changes just make a pull req and I'll republish it or feel free to publish your own version

**Comment by matronator** [comment]
Great, thanks! :)
